name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check Out Repo
              uses: actions/checkout@v3

            - name: Install .NET 6
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "6.0.x"

            - name: Install .NET 7
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "7.0.x"

            - name: Install .NET 8
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Build and Test
              run: ./build.sh test
